services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-converter-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - currency-converter-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: currency-converter-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - currency-converter-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: currency-converter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - currency-converter-network

volumes:
  redis_data:
    driver: local

networks:
  currency-converter-network:
    driver: bridge