services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-converter-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - currency-converter-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: currency-converter-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - currency-converter-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: currency-converter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - currency-converter-network

  influxdb:
    image: influxdb:2.7
    container_name: currency-converter-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=currency-org
      - DOCKER_INFLUXDB_INIT_BUCKET=currency-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - currency-converter-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: currency-converter-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - currency-converter-network

volumes:
  redis_data:
    driver: local
  influxdb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  currency-converter-network:
    driver: bridge