version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-converter-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - currency-converter-network

  nginx:
    image: nginx:alpine
    container_name: currency-converter-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - currency-converter-network

  mysql:
    image: mysql:8.0
    container_name: currency-converter-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: currency_converter
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: currency_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - currency-converter-network

  redis:
    image: redis:alpine
    container_name: currency-converter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - currency-converter-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  currency-converter-network:
    driver: bridge