services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-converter-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - currency-converter-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: currency-converter-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - currency-converter-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: currency-converter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - currency-converter-network
  
  influxdb:
    image: influxdb:2.7
    container_name: currency-converter-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdb_password_123
      - DOCKER_INFLUXDB_INIT_ORG=currency-converter
      - DOCKER_INFLUXDB_INIT_BUCKET=currency_converter
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=currency_converter_token_123
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - currency-converter-network

  grafana:
    image: grafana/grafana:latest
    container_name: currency-converter-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - currency-converter-network
    depends_on:
      - influxdb

volumes:
  redis_data:
    driver: local
  influxdb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  currency-converter-network:
    driver: bridge