apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    version: 2
    jsonData:
      version: Flux
      organization: currency-org
      defaultBucket: currency-metrics
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      token: my-super-secret-auth-token